=== milenachaine/projet_M2_IM_PYTHON/grammaire/qp/qp.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT QP (qp)+>
<!ATTLIST QP
  xmlns CDATA #FIXED ''>

<!ELEMENT qp (Geo_Point,Geo_Shape,C_NQPV,L_NQPV,C_CAINSEE,NOM_COM,C_DEP,
              Departement,D_MAJ,Nature_du_secteur,B_ETAT,B_VP,B_NPNRU,
              SHAPE_Leng,SHAPE_Area)>
<!ATTLIST qp
  xmlns CDATA #FIXED ''
  id CDATA #REQUIRED>

<!ELEMENT Geo_Point (#PCDATA)>
<!ATTLIST Geo_Point
  xmlns CDATA #FIXED ''>

<!ELEMENT Geo_Shape (#PCDATA)>
<!ATTLIST Geo_Shape
  xmlns CDATA #FIXED ''>

<!ELEMENT C_NQPV (#PCDATA)>
<!ATTLIST C_NQPV
  xmlns CDATA #FIXED ''>

<!ELEMENT L_NQPV (#PCDATA)>
<!ATTLIST L_NQPV
  xmlns CDATA #FIXED ''>

<!ELEMENT C_CAINSEE (#PCDATA)>
<!ATTLIST C_CAINSEE
  xmlns CDATA #FIXED ''>

<!ELEMENT NOM_COM (#PCDATA)>
<!ATTLIST NOM_COM
  xmlns CDATA #FIXED ''>

<!ELEMENT C_DEP (#PCDATA)>
<!ATTLIST C_DEP
  xmlns CDATA #FIXED ''>

<!ELEMENT Departement (#PCDATA)>
<!ATTLIST Departement
  xmlns CDATA #FIXED ''>

<!ELEMENT D_MAJ (#PCDATA)>
<!ATTLIST D_MAJ
  xmlns CDATA #FIXED ''>

<!ELEMENT Nature_du_secteur (#PCDATA)>
<!ATTLIST Nature_du_secteur
  xmlns CDATA #FIXED ''>

<!ELEMENT B_ETAT (#PCDATA)>
<!ATTLIST B_ETAT
  xmlns CDATA #FIXED ''>

<!ELEMENT B_VP (#PCDATA)>
<!ATTLIST B_VP
  xmlns CDATA #FIXED ''>

<!ELEMENT B_NPNRU (#PCDATA)>
<!ATTLIST B_NPNRU
  xmlns CDATA #FIXED ''>

<!ELEMENT SHAPE_Leng (#PCDATA)>
<!ATTLIST SHAPE_Leng
  xmlns CDATA #FIXED ''>

<!ELEMENT SHAPE_Area (#PCDATA)>
<!ATTLIST SHAPE_Area
  xmlns CDATA #FIXED ''>

=== milenachaine/projet_M2_IM_PYTHON/output/qp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE QP SYSTEM "qp.dtd">

<QP>
	<qp id="200">
		<Geo_Point>48.8747500053, 2.37067490689</Geo_Point>
		<Geo_Shape>"{""type"": ""Polygon"", ""coordinates"": [[[2.370548411290807, 48.877547944371614], [2.374374047199713, 48.874129935668265], [2.373354506966033, 48.87448277635608], [2.371450617661246, 48.874774177779464], [2.370435488477876, 48.87512890263576], [2.370471381946301, 48.87371513262671], [2.370711568776954, 48.87340925622425], [2.371410283024067, 48.87252354874638], [2.372006092432707, 48.87184482867736], [2.372888174777076, 48.872103005950315], [2.373459678002142, 48.872409667788276], [2.374398141695511, 48.872905666829325], [2.374480222085596, 48.873030463135684], [2.374708750184615, 48.87307117843721], [2.375198471385964, 48.872350154176566], [2.375587681447408, 48.8724933665059], [2.375875953567633, 48.872105616509316], [2.376091910357528, 48.87218125145202], [2.376333381055009, 48.871866355296454], [2.37635180745173, 48.87184600128801], [2.376222196550039, 48.87180052996941], [2.372943304615133, 48.87056776896762], [2.37111161419709, 48.86999720137938], [2.369580003027415, 48.87194544885202], [2.369642926623595, 48.87222479413925], [2.37027910053183, 48.87361107537082], [2.370271403117618, 48.873828360222646], [2.370075542903053, 48.87414399467887], [2.368625787614381, 48.87599131184488], [2.368241605358373, 48.8762035278567], [2.367511111503523, 48.87657918030094], [2.366359694376157, 48.87697487116224], [2.365936350834308, 48.87731125195246], [2.365999216129543, 48.87751299772143], [2.367584725827408, 48.87937499729377], [2.368063227327652, 48.87943177352207], [2.369749027853016, 48.8785259512912], [2.369897914792348, 48.878313798442015], [2.369921263188431, 48.87803960169111], [2.369976016416781, 48.87781195681084], [2.370234715642737, 48.87761011836387], [2.370548411290807, 48.877547944371614]]]}"</Geo_Shape>
		<C_NQPV>QV999907</C_NQPV>
		<L_NQPV>Grange-aux-Belles</L_NQPV>
		<C_CAINSEE>75110</C_CAINSEE>
		<NOM_COM>PARIS-10E-ARRONDISSEMENT</NOM_COM>
		<C_DEP>75</C_DEP>
		<Departement>PARIS</Departement>
		<D_MAJ>2015-07-01T00:00:00.000Z</D_MAJ>
		<Nature_du_secteur>QVA</Nature_du_secteur>
		<B_ETAT>O</B_ETAT>
		<B_VP>O</B_VP>
		<B_NPNRU>N</B_NPNRU>
		<SHAPE_Leng>3657.8720662224073</SHAPE_Leng>
		<SHAPE_Area>232374.73116314178</SHAPE_Area>
	</qp>
	<qp id="226">
		<Geo_Point>48.8769638761, 2.37307473232</Geo_Point>
		<Geo_Shape>"{""type"": ""Polygon"", ""coordinates"": [[[2.373954948865217, 48.877563228301035], [2.37401649349066, 48.877302427226326], [2.37416353215295, 48.876947896736866], [2.374232643285572, 48.87659724035753], [2.374254837793088, 48.87637047894502], [2.374186539589966, 48.87611327955473], [2.373709821661309, 48.87528032821965], [2.371263639399531, 48.87739501853142], [2.371657074210085, 48.87759827658044], [2.372017303788303, 48.87732620227579], [2.372197102510207, 48.877485531254486], [2.372008116739463, 48.8780881195721], [2.373122839307641, 48.8782181021266], [2.373990387356301, 48.87785450131351], [2.373954948865217, 48.877563228301035]]]}"</Geo_Shape>
		<C_NQPV>QP075002</C_NQPV>
		<L_NQPV>Chaufourniers</L_NQPV>
		<C_CAINSEE>75119</C_CAINSEE>
		<NOM_COM>PARIS-19E-ARRONDISSEMENT</NOM_COM>
		<C_DEP>75</C_DEP>
		<Departement>PARIS</Departement>
		<D_MAJ>2014-09-02T00:00:00.000Z</D_MAJ>
		<Nature_du_secteur>NQPV</Nature_du_secteur>
		<B_ETAT>O</B_ETAT>
		<B_VP>O</B_VP>
		<B_NPNRU>N</B_NPNRU>
		<SHAPE_Leng>916.8615856260391</SHAPE_Leng>
		<SHAPE_Area>38793.140586984824</SHAPE_Area>
	</qp>
	<qp id="237">
		<Geo_Point>48.8884455681, 2.38209046009</Geo_Point>
		<Geo_Shape>"{""type"": ""Polygon"", ""coordinates"": [[[2.379635016704814, 48.888168894692505], [2.383083233093898, 48.8898897535497], [2.383704572464641, 48.889362289632274], [2.384289819888333, 48.88826076661949], [2.380788924946546, 48.88716089856989], [2.379635016704814, 48.888168894692505]]]}"</Geo_Shape>
		<C_NQPV>QV999905</C_NQPV>
		<L_NQPV>Ourcq Léon Giraux</L_NQPV>
		<C_CAINSEE>75119</C_CAINSEE>
		<NOM_COM>PARIS-19E-ARRONDISSEMENT</NOM_COM>
		<C_DEP>75</C_DEP>
		<Departement>PARIS</Departement>
		<D_MAJ>2015-01-23T00:00:00.000Z</D_MAJ>
		<Nature_du_secteur>AQV</Nature_du_secteur>
		<B_ETAT>O</B_ETAT>
		<B_VP>O</B_VP>
		<B_NPNRU>N</B_NPNRU>
		<SHAPE_Leng>945.9605949068657</SHAPE_Leng>
		<SHAPE_Area>52460.07903726834</SHAPE_Area>
	</qp>
	<qp id="247">
		<Geo_Point>48.8695023639, 2.3984178305</Geo_Point>
		<Geo_Shape>"{""type"": ""Polygon"", ""coordinates"": [[[2.395806501075365, 48.87005802186667], [2.397401005528716, 48.87023369622391], [2.399241295652299, 48.8708063699113], [2.400610464481232, 48.86911401960473], [2.399606484035289, 48.86863651924804], [2.398056291464244, 48.86819608168778], [2.395806501075365, 48.87005802186667]]]}"</Geo_Shape>
		<C_NQPV>QV999906</C_NQPV>
		<L_NQPV>140 Ménilmontant</L_NQPV>
		<C_CAINSEE>75120</C_CAINSEE>
		<NOM_COM>PARIS-20E-ARRONDISSEMENT</NOM_COM>
		<C_DEP>75</C_DEP>
		<Departement>PARIS</Departement>
		<D_MAJ>2015-01-23T00:00:00.000Z</D_MAJ>
		<Nature_du_secteur>AQV</Nature_du_secteur>
		<B_ETAT>O</B_ETAT>
		<B_VP>O</B_VP>
		<B_NPNRU>N</B_NPNRU>
		<SHAPE_Leng>960.527846230314</SHAPE_Leng>
		<SHAPE_Area>54514.53501033864</SHAPE_Area>
	</qp>
	<qp id="251">
		<Geo_Point>48.8692911805, 2.37785076507</Geo_Point>
		<Geo_Shape>"{""type"": ""Polygon"", ""coordinates"": [[[2.383154273402918, 48.867039145320874], [2.382885677506997, 48.86698395231875], [2.382520285575678, 48.866908867794805], [2.380246139843079, 48.86634987929338], [2.378549411095006, 48.86802472072658], [2.378429217916699, 48.868008288010756], [2.377524898043183, 48.869198890897756], [2.376333720212077, 48.868831707164034], [2.374938071535551, 48.868428539465505], [2.373924305024428, 48.86947808573589], [2.372943304615133, 48.87056776896762], [2.376222196550039, 48.87180052996941], [2.37635180745173, 48.87184600128801], [2.376342594931418, 48.871856178745865], [2.377002732618512, 48.872048492330116], [2.377978196306178, 48.87109456580296], [2.37879549578303, 48.87044905526757], [2.38055900719345, 48.86906701969774], [2.382981583862103, 48.867254884560175], [2.383081197937712, 48.86718047855624], [2.383154273402918, 48.867039145320874]]]}"</Geo_Shape>
		<C_NQPV></C_NQPV>
		<L_NQPV>Grand Belleville 11e</L_NQPV>
		<C_CAINSEE>75111</C_CAINSEE>
		<NOM_COM>PARIS-11E-ARRONDISSEMENT</NOM_COM>
		<C_DEP>75</C_DEP>
		<Departement>PARIS</Departement>
		<D_MAJ>2015-07-01T00:00:00.000Z</D_MAJ>
		<Nature_du_secteur>NQPV</Nature_du_secteur>
		<B_ETAT>N</B_ETAT>
		<B_VP>O</B_VP>
		<B_NPNRU>N</B_NPNRU>
		<SHAPE_Leng>2155.8841023128816</SHAPE_Leng>
		<SHAPE_Area>180798.09999343762</SHAPE_Area>
	</qp>
	<qp id="253">
		<Geo_Point>48.8733792836, 2.35268847234</Geo_Point>
		<Geo_Shape>"{""type"": ""Polygon"", ""coordinates"": [[[2.358293167145589, 48.873732220147446], [2.355620579400862, 48.86918402460916], [2.34794890428401, 48.87077602257249], [2.347981987721275, 48.8740006667278], [2.348306138224367, 48.87578379931714], [2.348970169407912, 48.87715046667927], [2.34974725983504, 48.8773532534239], [2.355380518947941, 48.876562313631524], [2.356157400034667, 48.87617778673855], [2.358293167145589, 48.873732220147446]]]}"</Geo_Shape>
		<C_NQPV>QV000660</C_NQPV>
		<L_NQPV>Les Portes</L_NQPV>
		<C_CAINSEE>75110</C_CAINSEE>
		<NOM_COM>PARIS-10E-ARRONDISSEMENT</NOM_COM>
		<C_DEP>75</C_DEP>
		<Departement>PARIS</Departement>
		<D_MAJ>2015-07-01T00:00:00.000Z</D_MAJ>
		<Nature_du_secteur>QVA</Nature_du_secteur>
		<B_ETAT>O</B_ETAT>
		<B_VP>O</B_VP>
		<B_NPNRU>N</B_NPNRU>
		<SHAPE_Leng>2719.0075508973073</SHAPE_Leng>
		<SHAPE_Area>510396.0325230572</SHAPE_Area>
	</qp>
	<qp id="254">
		<Geo_Point>48.8705027763, 2.37961442472</Geo_Point>
